### ISSUE TITLE
How could i run this code section from this project?

### ISSUE THREAD

**Issue by ezrawilliam** [Hyperparticle/graph-nlu#1]
So, i already tried to run your babi_dialogue_ridge.ipynb notebooks, and so far i do some trial and error, but i just can't seem to solve this part of your code : 

import operator
import scipy
import sklearn

eval_data = dev_data
gold=[]
guess=[]

indeces = list(set(eval_data.index))
print('num instances', len(indeces))
mrr = 0.0
for eid in indeces:
    sub = rdata[rdata.index == eid] # grab the RE for this scene
    target = compute_target(sub) # compose the predictions of each word to a target vector
    distances = [(v['rname'], scipy.spatial.distance.cosine(target,v.ix[start_col:])) for i,v in restaurants.iterrows()]
    distances.sort(key=operator.itemgetter(1))
    guess += [distances[0][0]]
    d = list(zip(*distances))[0]
    mrr += compute_mrr(d, sub.iloc[-1].ix['target'])
    gold += [sub.iloc[-1].ix['target']] # all the rows in sub have the same matrix
    
when i run it, it will give me this: 

AttributeError                            Traceback (most recent call last)
<ipython-input-47-7f7e33af25a1> in <module>()
     13     sub = rdata[rdata.index == eid] # grab the RE for this scene
     14     target = compute_target(sub) # compose the predictions of each word to a target vector
---> 15     distances = [(v['rname'], scipy.spatial.distance.cosine(target,v.ix[start_col:])) for i,v in restaurants.iterrows()]
     16     distances.sort(key=operator.itemgetter(1))
     17     guess += [distances[0][0]]

<ipython-input-47-7f7e33af25a1> in <listcomp>(.0)
     13     sub = rdata[rdata.index == eid] # grab the RE for this scene
     14     target = compute_target(sub) # compose the predictions of each word to a target vector
---> 15     distances = [(v['rname'], scipy.spatial.distance.cosine(target,v.ix[start_col:])) for i,v in restaurants.iterrows()]
     16     distances.sort(key=operator.itemgetter(1))
     17     guess += [distances[0][0]]

~\Anaconda3\lib\site-packages\scipy\spatial\distance.py in cosine(u, v, w)
    742     # cosine distance is also referred to as 'uncentered correlation',
    743     #   or 'reflective correlation'
--> 744     return correlation(u, v, w=w, centered=False)
    745 
    746 

~\Anaconda3\lib\site-packages\scipy\spatial\distance.py in correlation(u, v, w, centered)
    693         u = u - umu
    694         v = v - vmu
--> 695     uv = np.average(u * v, weights=w)
    696     uu = np.average(np.square(u), weights=w)
    697     vv = np.average(np.square(v), weights=w)

~\Anaconda3\lib\site-packages\numpy\lib\function_base.py in average(a, axis, weights, returned)
   1127     if weights is None:
   1128         avg = a.mean(axis)
-> 1129         scl = avg.dtype.type(a.size/avg.size)
   1130     else:
   1131         wgt = np.asanyarray(weights)

AttributeError: 'float' object has no attribute 'dtype'

Help, anyone?

**Comment by Hyperparticle** [comment]
It appears to be an error in the `scipy` library. It's possible that you are running a version of `scipy` that has changed its semantics (or introduced a bug). What version of the library are you running? I'll see if I can reproduce the issue.

**Comment by ezrawilliam** [comment]
Looks like i'm using the 1.1.0 version of the scipy library here

**Comment by ezrawilliam** [comment]
Ok, i solved the problem by myself now. It seems that this is a package error. I succesfully run all of your code with 1.13.3 numpy version and 0.19.1 scipy version

**Comment by Hyperparticle** [comment]
Excellent. I was going to run the code, but I see you solved the problem. The code should include explicit version numbers in the future.

**Comment by DianaSM44** [comment]
Any updates on this? What are the current correct numpy and scipy versions to run spatial.distance.cosine without this error?

**Comment by Hyperparticle** [comment]
I think wrapping both arguments with `np.array()` should do the trick. Or maybe you can try scipy 0.19.1.
